AWSTemplateFormatVersion: 2010-09-09
Description: Configuration on base VPC Network.
Parameters:
  ProjectName:
    Description: Provide name of the project.
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: '^[a-zA-Z][-a-zA-Z0-9]*$'
  Environment:
    Description: 'Input your Environment (e.g. Prod, UAT, etc.)'
    Type: String
    MaxLength: 10
    Default: Dev
  VpcCIDR:
    Description: CIDR block of VPC
    Type: String
    AllowedPattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$'
  Subnet01CIDR:
    Description: CIDR block of first Subnet
    Type: String
    AllowedPattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$'
  Subnet02CIDR:
    Description: CIDR block of second Subnet
    Type: String
    AllowedPattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$'
  Subnet03CIDR:
    Description: CIDR block of third Subnet
    Type: String
    AllowedPattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Background Information
        Parameters:
          - ProjectName
          - Environment
      - Label:
          default: Network Configuration
        Parameters:
          - VpcCIDR
          - Subnet01CIDR
          - Subnet02CIDR
          - Subnet03CIDR
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Join 
            - '-'
            - - !Ref ProjectName
              - !Ref Environment
              - VPC
  SN01:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: ap-southeast-1a
      CidrBlock: !Ref Subnet01CIDR
      Tags:
        - Key: Name
          Value: !Join 
            - '-'
            - - !Ref ProjectName
              - !Ref Environment
              - SN-01
      VpcId: !Ref VPC
  SN02:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: ap-southeast-1b
      CidrBlock: !Ref Subnet02CIDR
      Tags:
        - Key: Name
          Value: !Join 
            - '-'
            - - !Ref ProjectName
              - !Ref Environment
              - SN-02
      VpcId: !Ref VPC
  SN03:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: ap-southeast-1c
      CidrBlock: !Ref Subnet03CIDR
      Tags:
        - Key: Name
          Value: !Join 
            - '-'
            - - !Ref ProjectName
              - !Ref Environment
              - SN-03
      VpcId: !Ref VPC
  IGW:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: !Join 
            - '-'
            - - !Ref ProjectName
              - !Ref Environment
              - IGW
  IGWAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref IGW
      VpcId: !Ref VPC
  RT:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Join 
            - '-'
            - - !Ref ProjectName
              - !Ref Environment
              - RT
  Route:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW
      RouteTableId: !Ref RT
  RTAssociation01:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref SN01
      RouteTableId: !Ref RT
  RTAssociation02:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref SN02
      RouteTableId: !Ref RT
  RTAssociation03:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref SN03
      RouteTableId: !Ref RT
Outputs:
  VpcId:
    Description: ID of the created VPC
    Value: !Ref VPC
    Export:
      Name: !Sub '${AWS::StackName}-VPCID'
  Subnet01:
    Description: The first subnet ID
    Value: !Ref SN01
    Export:
      Name: !Sub '${AWS::StackName}-SubnetID01'
  Subnet02:
    Description: The second subnet ID
    Value: !Ref SN02
    Export:
      Name: !Sub '${AWS::StackName}-SubnetID02'
  Subnet03:
    Description: The thrid subnet ID
    Value: !Ref SN03
    Export:
      Name: !Sub '${AWS::StackName}-SubnetID03'
